-- Role: job_user
-- DROP ROLE IF EXISTS job_user;

CREATE ROLE job_user WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  NOBYPASSRLS
  ENCRYPTED PASSWORD '7410'